"""State WARN data source configurations.

All 50 states + DC with verified URLs, data formats, and scrape schedules.
Format types: excel, html, csv, pdf, js_fallback
Schedule tiers: daily (high-vol), twice_weekly (medium), weekly (low-vol)
"""

from src.data_ingestion.collectors.warn.models import StateWARNConfig

STATE_NAME_TO_CODE: dict[str, str] = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
    "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
    "District of Columbia": "DC", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI",
    "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME",
    "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN",
    "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE",
    "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM",
    "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI",
    "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX",
    "Utah": "UT", "Vermont": "VT", "Virginia": "VA", "Washington": "WA",
    "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY",
    "Puerto Rico": "PR", "Virgin Islands": "VI", "Guam": "GU",
    "Washington, D.C.": "DC", "Washington DC": "DC", "D.C.": "DC",
}

CONSOLIDATED_CURRENT_YEAR_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1q47pIyvmtY7GtF3-7mHOrqBe_0uot_G944XELZ_3raU/export?format=csv"
)
CONSOLIDATED_HISTORICAL_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1B1CYZFyJ1ghK1ApuXEeGKo3mLYWzLwONvmWV8Plkav8/export?format=csv"
)

STATE_CONFIGS: dict[str, StateWARNConfig] = {
    # === EXCEL STATES (most reliable -- direct file downloads) ===
    "CA": StateWARNConfig(
        state_code="CA",
        name="California",
        url="https://edd.ca.gov/siteassets/files/jobs_and_training/warn/warn_report.xlsx",
        format="excel",
        parser="parse_california",
        schedule_tier="daily",
        notes="California EDD Excel file with all active WARN notices",
    ),
    "TX": StateWARNConfig(
        state_code="TX",
        name="Texas",
        url="https://www.twc.texas.gov/files/businesses/warn-act-listings-702.xlsx",
        format="excel",
        parser="parse_texas",
        schedule_tier="daily",
        notes="Texas Workforce Commission Excel file",
    ),
    "IL": StateWARNConfig(
        state_code="IL",
        name="Illinois",
        url="https://www.illinoisworknet.com/ILESWIC/Pages/WARN.aspx",
        format="html",
        parser="parse_generic_html",
        schedule_tier="daily",
        notes="Illinois WorkNet HTML page with table",
    ),
    "IA": StateWARNConfig(
        state_code="IA",
        name="Iowa",
        url="https://www.iowaworkforcedevelopment.gov/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Iowa Workforce Development HTML page",
    ),
    "KY": StateWARNConfig(
        state_code="KY",
        name="Kentucky",
        url="https://kcc.ky.gov/employer/Pages/WARN-Notices.aspx",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Kentucky Career Center HTML page",
    ),
    "MT": StateWARNConfig(
        state_code="MT",
        name="Montana",
        url="https://wsd.dli.mt.gov/wioa/warnnotice",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Montana Workforce Services HTML page",
    ),
    "NY": StateWARNConfig(
        state_code="NY",
        name="New York",
        url="https://dol.ny.gov/warn-notices",
        format="html",
        parser="parse_newyork",
        schedule_tier="daily",
        notes="New York DOL HTML page",
    ),
    "OR": StateWARNConfig(
        state_code="OR",
        name="Oregon",
        url="https://data.oregon.gov/api/views/ny3c-htih/rows.csv?accessType=DOWNLOAD",
        format="csv",
        parser="parse_oregon_csv",
        schedule_tier="weekly",
        notes="Oregon Socrata open data portal CSV endpoint",
    ),
    "RI": StateWARNConfig(
        state_code="RI",
        name="Rhode Island",
        url="https://dlt.ri.gov/employers/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Rhode Island DLT HTML page",
    ),
    # === CSV STATES ===
    "VA": StateWARNConfig(
        state_code="VA",
        name="Virginia",
        url="https://www.vec.virginia.gov/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Virginia Employment Commission HTML page",
    ),
    # === HTML TABLE STATES (generic parser) ===
    "FL": StateWARNConfig(
        state_code="FL",
        name="Florida",
        url="https://floridajobs.org/office-directory/division-of-workforce-services/workforce-programs/reemployment-and-emergency-assistance-coordination-team-react/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="daily",
        notes="Florida DEO HTML page",
    ),
    "PA": StateWARNConfig(
        state_code="PA",
        name="Pennsylvania",
        url="https://www.dli.pa.gov/Individuals/Workforce-Development/warn/Pages/default.aspx",
        format="html",
        parser="parse_generic_html",
        schedule_tier="daily",
        notes="Pennsylvania L&I HTML table",
    ),
    "OH": StateWARNConfig(
        state_code="OH",
        name="Ohio",
        url="https://jfs.ohio.gov/warn/index.stm",
        format="html",
        parser="parse_generic_html",
        schedule_tier="daily",
        notes="Ohio JFS HTML page",
    ),
    "GA": StateWARNConfig(
        state_code="GA",
        name="Georgia",
        url="https://www.dol.state.ga.us/public/es/warn/searchwarns/list",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Georgia DOL WARN listing page",
    ),
    "MI": StateWARNConfig(
        state_code="MI",
        name="Michigan",
        url="https://milmi.org/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Michigan LMI HTML page",
    ),
    "NJ": StateWARNConfig(
        state_code="NJ",
        name="New Jersey",
        url="https://www.nj.gov/labor/employer-services/warn/warn-notices/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="New Jersey DOL HTML page",
    ),
    "WA": StateWARNConfig(
        state_code="WA",
        name="Washington",
        url="https://esd.wa.gov/about-employees/WARN",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Washington ESD HTML page",
    ),
    "MA": StateWARNConfig(
        state_code="MA",
        name="Massachusetts",
        url="https://www.mass.gov/info-details/worker-adjustment-and-retraining-notification-act-warn",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Massachusetts WARN page",
    ),
    "TN": StateWARNConfig(
        state_code="TN",
        name="Tennessee",
        url="https://www.tn.gov/workforce/general-resources/warn.html",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Tennessee Department of Labor HTML page",
    ),
    "IN": StateWARNConfig(
        state_code="IN",
        name="Indiana",
        url="https://www.in.gov/dwd/warn-notices/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Indiana DWD WARN page",
    ),
    "MO": StateWARNConfig(
        state_code="MO",
        name="Missouri",
        url="https://jobs.mo.gov/employer/warn",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Missouri Jobs WARN page",
    ),
    "MD": StateWARNConfig(
        state_code="MD",
        name="Maryland",
        url="https://www.dllr.state.md.us/employment/warn.shtml",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Maryland DLLR WARN page",
    ),
    "WI": StateWARNConfig(
        state_code="WI",
        name="Wisconsin",
        url="https://dwd.wisconsin.gov/dislocatedworker/warn/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Wisconsin DWD WARN page",
    ),
    "CO": StateWARNConfig(
        state_code="CO",
        name="Colorado",
        url="https://cdle.colorado.gov/employers/layoff-assistance/warn-act",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Colorado DLE WARN page",
    ),
    "MN": StateWARNConfig(
        state_code="MN",
        name="Minnesota",
        url="https://mn.gov/deed/programs-services/dislocated-worker/warn-info/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="Minnesota DEED WARN page",
    ),
    "NC": StateWARNConfig(
        state_code="NC",
        name="North Carolina",
        url="https://www.nccommerce.com/documents/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="twice_weekly",
        notes="North Carolina Commerce page -- may link to PDFs",
    ),
    "SC": StateWARNConfig(
        state_code="SC",
        name="South Carolina",
        url="https://www.scworks.org/employer/rapid-response.html",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="South Carolina Works WARN page",
    ),
    "AL": StateWARNConfig(
        state_code="AL",
        name="Alabama",
        url="https://www.labor.alabama.gov/warn_notices.aspx",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Alabama DOL WARN page",
    ),
    "LA": StateWARNConfig(
        state_code="LA",
        name="Louisiana",
        url="https://www.laworks.net/WARN/WARN.asp",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Louisiana Workforce Commission WARN page",
    ),
    "CT": StateWARNConfig(
        state_code="CT",
        name="Connecticut",
        url="https://www.ctdol.state.ct.us/progsupt/bussrvce/warn/warn.htm",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Connecticut DOL WARN page",
    ),
    "UT": StateWARNConfig(
        state_code="UT",
        name="Utah",
        url="https://jobs.utah.gov/employer/layoff/warn.html",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Utah DWS WARN page",
    ),
    "NV": StateWARNConfig(
        state_code="NV",
        name="Nevada",
        url="https://detr.nv.gov/Page/WARN_Notifications",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Nevada DETR WARN page",
    ),
    "AR": StateWARNConfig(
        state_code="AR",
        name="Arkansas",
        url="https://www.dws.arkansas.gov/employers/warn-notices/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Arkansas DWS WARN page",
    ),
    "MS": StateWARNConfig(
        state_code="MS",
        name="Mississippi",
        url="https://mdes.ms.gov/employers/employer-services/warn-notices/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Mississippi DES WARN page",
    ),
    "NE": StateWARNConfig(
        state_code="NE",
        name="Nebraska",
        url="https://dol.nebraska.gov/Employer/LawsAndRegs/WARNNotices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Nebraska DOL WARN page",
    ),
    "WV": StateWARNConfig(
        state_code="WV",
        name="West Virginia",
        url="https://workforcewv.org/employer-services/warn-act/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="West Virginia Workforce WARN page",
    ),
    "HI": StateWARNConfig(
        state_code="HI",
        name="Hawaii",
        url="https://labor.hawaii.gov/wdc/warn-notices/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Hawaii WDC WARN page",
    ),
    "NH": StateWARNConfig(
        state_code="NH",
        name="New Hampshire",
        url="https://www.nhes.nh.gov/employers/warn.htm",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="New Hampshire Employment Security WARN page",
    ),
    "SD": StateWARNConfig(
        state_code="SD",
        name="South Dakota",
        url="https://dlr.sd.gov/workforce_services/businesses/warn_notices.aspx",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="South Dakota DLR WARN page",
    ),
    "ND": StateWARNConfig(
        state_code="ND",
        name="North Dakota",
        url="https://www.jobsnd.com/employers/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="North Dakota Job Service WARN page",
    ),
    "AK": StateWARNConfig(
        state_code="AK",
        name="Alaska",
        url="https://jobs.alaska.gov/rr/warn.html",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Alaska DOLWD WARN page",
    ),
    "WY": StateWARNConfig(
        state_code="WY",
        name="Wyoming",
        url="https://dws.wyo.gov/employers/warn-notices/",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Wyoming DWS WARN page",
    ),
    "DC": StateWARNConfig(
        state_code="DC",
        name="District of Columbia",
        url="https://does.dc.gov/service/warn-notices",
        format="html",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="DC DOES WARN page",
    ),
    # === PDF STATES ===
    "ID": StateWARNConfig(
        state_code="ID",
        name="Idaho",
        url="https://www.labor.idaho.gov/businesses/warn-notifications/",
        format="pdf",
        parser="parse_idaho_pdf",
        schedule_tier="weekly",
        notes="Idaho DOL -- page links to PDFs",
    ),
    "NM": StateWARNConfig(
        state_code="NM",
        name="New Mexico",
        url="https://www.dws.state.nm.us/en-us/Rapid-Response",
        format="pdf",
        parser="parse_newmexico_pdf",
        schedule_tier="weekly",
        notes="New Mexico DWS -- links to PDF notices",
    ),
    # === JAVASCRIPT / JOBCENTER STATES (fall back to layoffdata.com) ===
    "AZ": StateWARNConfig(
        state_code="AZ",
        name="Arizona",
        url="https://www.azjobconnection.gov/search/warn_lookups/new",
        format="js_fallback",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Jobcenter platform -- requires JS, fallback to consolidated",
    ),
    "DE": StateWARNConfig(
        state_code="DE",
        name="Delaware",
        url="https://labor.delaware.gov/divisions/employment-training/warn-notices/",
        format="js_fallback",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Delaware DOL -- JS rendered, fallback to consolidated",
    ),
    "KS": StateWARNConfig(
        state_code="KS",
        name="Kansas",
        url="https://www.kansasworks.com/ada/mn_warn_dsp.cfm",
        format="js_fallback",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Kansas Works -- Jobcenter platform, fallback to consolidated",
    ),
    "ME": StateWARNConfig(
        state_code="ME",
        name="Maine",
        url="https://www.maine.gov/labor/rr/warn.html",
        format="js_fallback",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Maine DOL -- may need JS, fallback to consolidated",
    ),
    "OK": StateWARNConfig(
        state_code="OK",
        name="Oklahoma",
        url="https://oklahoma.gov/oesc/businesses-employers/warn-notices.html",
        format="js_fallback",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Oklahoma OESC -- Jobcenter platform, fallback to consolidated",
    ),
    "VT": StateWARNConfig(
        state_code="VT",
        name="Vermont",
        url="https://labor.vermont.gov/employers/warn-notices",
        format="js_fallback",
        parser="parse_generic_html",
        schedule_tier="weekly",
        notes="Vermont DOL -- Jobcenter platform, fallback to consolidated",
    ),
}

JS_FALLBACK_STATES = frozenset(
    code for code, cfg in STATE_CONFIGS.items() if cfg.format == "js_fallback"
)

SCHEDULE_TIERS: dict[str, str] = {
    "daily": "0 12 * * *",
    "twice_weekly": "0 12 * * 1,4",
    "weekly": "0 8 * * 3",
}
